### ISSUE TITLE
Create sample NeuroML connectome output

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#114]
- [x] install NEURON and NeuroConstruct
- [ ] load the connectome up in NEURON
- [ ] set NEURON to write out data files for the voltage of all 302 neurons
- [ ] graph the dataset using matplotlib to see all traces
- [ ] upload graph and data files to GitHub
- [ ] repeat data output, graphing and uploading steps for all compartments (302 x ~10)

**Comment by slarson** [comment]
This all happens now within c302.  Closing this.

**Comment by Dartomic** [comment]
> Thanks for setting that up.
> 
> Need to emphasize again: the neuroConstruct project, and hence the NEURON simulation it generated, **does not yet produce electrically realistic behaviour**. All the cells are passive (no voltage dependent ion channels) and the synapses are first guesses, based on vertebrate chemical synapses; invertebrates have more graded synaptic transmission.
> 
> So while getting NEURON to produce voltage traces is useful, the activity patterns are meaningless until we have more detailed cell & synapse models.

I hope it is ok to ask this here. But is this still true? I see graphs that show spiking, but I have not read enough to know if it is the neurons doing it, or if the software is stimulating the models in spiking patterns.

**Comment by pgleeson** [comment]
@Dartomic Certainly ignore the old neuroConstruct version, except for visualising the 3D structure of the cells/network. c302 has replaced all of this.

Re physiological realism of the responses, see https://github.com/openworm/c302/blob/master/examples/parametersweep/README.md, but again this is only "realistic" in that the neurons don't spike, and the muscle cells do. Much more has to be done to match these to experimental measurements of cell behaviour, but they're a good place to start in terms of using them in a network and having some output.

**Comment by Dartomic** [comment]
I didnt realize neuron types exist that do not produce action potentials. That makes the graphs make a lot more sense to me now. Well that may somewhat change what I was going to use the neuron models for.

**Comment by pgleeson** [comment]
Most neurons don't spike, but some do, see: https://www.cell.com/cell/fulltext/S0092-8674(18)31034-1.

The transmission of information between neurons at the synapses is generally more gradual and continuous in C. elegans than in spiking neuron networks, which is generally how vertebrate systems are modelled (these have specific action potentials which trigger neurotransmitter release at a specific time causing a short, decaying current into the post synaptic cell).
