### ISSUE TITLE
update RegenerateConnectome.py to read data from OpenWorm database instead of a spreadsheet

### ISSUE THREAD

**Issue by kneuron** [openworm/OpenWorm#140]
## Issue
Currently, [RegenerateConnectome.py](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/RegenerateConnectome.py) reads synapse position data from a spreadsheet. (I think this one: [Steven Cook Data](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdGxoRE0wYURfYlBpM21Lb2VHOGxjQlE#gid=0) ). See [issue 136](https://github.com/openworm/OpenWorm/issues/136) for more info. This issue is effectively update "a)" from that issue.

In order to close the data->model loop, we should replace this step with one that reads the data from our currently in-development [biological data database](https://groups.google.com/d/msg/openworm-discuss/2V5kF5na5fw/GnxZMgWYF7wJ)

## motivation
This will serve as the first test case for closing the loop between the biological data repository we are aggregating from the scientific literature and the simulations we plan to run to explore and test this data.

## steps
1. make sure Cook's Data is in the database - upload it if not
2. #143 - create script to query and present data from the semantic database as RDF  
3. appropriately represent RDF data to RegenerateConnectome.py (either by munging the RDF into the format that RegenerateConnectome.py is already expecting, or modifying RegenerateConnectome.py to work with RDF)

**Comment by 16zzundel5** [comment]
Hi-- what's the latest status on this? I can work on this if you need someone.

**Comment by slarson** [comment]
@16zzundel5 this did get done in draft form in relation to the [PyOpenWorm](https://github.com/openworm/PyOpenWorm) effort.  If you'd like to help out with this, come join us over in [the chat room](https://gitter.im/openworm/PyOpenWorm).  Thanks!
