### ISSUE TITLE
Port Matlab functions from SegWorm code base that generate statistics from worm skeletons

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#142]
[This matlab file](https://github.com/openworm/SegWorm/blob/master/Worms/Statistics/wormStats2Matrix.m) seems to be core to generating statistics from a worm skeleton.  If we can implement this in Python, we would have a means to compare the OpenWorm simulation in the same way that the [WormBehavior database](http://www.ncbi.nlm.nih.gov/pubmed/23852451) compared its movies to each other.

Let's try to break up the porting into small chunks that aren't too menacing.

**Comment by slarson** [comment]
@JimHokanson @MichaelCurrie -- is this obsolete now superseded by issues in the movement validation repo?

**Comment by JimHokanson** [comment]
@slarson Yes, this is now obsolete. See https://github.com/openworm/movement_validation/issues/76
