### ISSUE TITLE
Improve performance of PCISPH kernel

### ISSUE THREAD

**Issue by vellamike** [openworm/OpenWorm#165]
The `PCISPH` kernel in sphFluid.cl takes approximately 40% of execution time on a multi-core machine and significantly more on other architectures. The kernel is unfortunately also not well-documented.

General Sibernetic performance boosts have already been discussed in #74. I wonder if we could squeeze out some more performance boosts?

**Comment by slarson** [comment]
Sibernetic performance issues are continuing to be worked on over in the [Sibernetic repo](https://github.com/openworm/sibernetic); closing them off of here.
