### ISSUE TITLE
execute runSort() in openCL

### ISSUE THREAD

**Issue by Neurophile** [openworm/OpenWorm#166]
The current sort is executed thusly:
```
	copy_buffer_from_device( _particleIndex, particleIndex, PARTICLE_COUNT * 2 * sizeof( int ) );
	qsort( _particleIndex, PARTICLE_COUNT, 2 * sizeof( int ), myCompare );
	copy_buffer_to_device( _particleIndex, particleIndex, PARTICLE_COUNT * 2 * sizeof( int ) );
```
The round trip of the buffer data is not strictly necessary. On a GPU platform this will be a big performance hit.

**Comment by slarson** [comment]
Sibernetic performance issues are continuing to be worked on over in the [Sibernetic repo](https://github.com/openworm/sibernetic); closing them off of here.
