### ISSUE TITLE
Port latest membrane development from Sibernetic to Geppetto

### ISSUE THREAD

**Issue by tarelli** [openworm/OpenWorm#171]
The latest development (which includes the model of the worm body developed by @a-palyanov and that allows for it to wiggle) has to be ported to [Geppetto](http://geppetto.org). There is already a codebase working for PCISPH in Geppetto which was ported by @gidili, this version includes both liquid and elastic matter. This task involves knowing C++ and Java, contributors are welcome.

**Comment by slarson** [comment]
This is being tracked over here: https://github.com/openworm/org.geppetto.model.sph/pull/19

**Comment by slarson** [comment]
Obsolete
