### ISSUE TITLE
Define schema and format for the recording of a simulation

### ISSUE THREAD

**Issue by tarelli** [openworm/OpenWorm#172]
Requirements
- The record of a simulation needs to specify the variables and parameters which are contained in the recording.
- The information in the file needs to be sufficient to map back the simulation results to the model which was originally simulated, i.e. if the simulation of the NeuroML network of the celegans is recorded then we need to be able to associate the recording to the appropriate cells
- The format should be usable to record different types of simulation, e.g. it should be the same for both PCI-SPH and a Neuronal simulation since every simulation recording boils down to state-variables and time series
- Since the recordings can be quite big the format needs to be optimised for high-volume data (HDF5?)

What needs to be done:

1) Review of possible formats already existing, see if there's anything suitable that can be just reused, if yes GOTO 4.
2) Define a Meta-Model
3) Review the meta-model
4) Write scripts that can save the outcome of a PCISPH simulation in the agreed format 
5) Write scripts that can save the outcome of a neuronal simulation in the agreed format 
(look into building on top of neuroConstruct functionality for this)

The task list for what needs to be done in Geppetto to read this format and stream it will be captured in a separate issue.

Note: This is not the format that will be used to stream to the Geppetto frontend, this is the format in which the simulations are persisted. The discussion about compressing the data exchanged between the server and the frontend in Geppetto is happening [here](https://github.com/openworm/org.geppetto/issues/9).

**Comment by slarson** [comment]
Obsolete.  Would be good to track the most recent efforts along these lines in an updated issue though.
