### ISSUE TITLE
Update build_dev_environement to include neuronal simulator

### ISSUE THREAD

**Issue by tarelli** [openworm/OpenWorm#174]
https://github.com/openworm/OpenWorm/blob/master/utilities/build_dev_environment.py needs to be update to include the neuronal simulator. Its baby brother, https://github.com/openworm/OpenWorm/blob/master/utilities/build_server_package.py is already updated so it would be a matter of copying the relevant bits over.

**Comment by slarson** [comment]
I believe this is now obsolete.
