### ISSUE TITLE
Make it so worm body model can receive muscle activations from c302

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#177]
In the current Sibernetic code base, the muscles are activated by [simple sine functions](https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/master/src/main_sim.py#L25).

We want to replace the sinusoidal input with input from the [c302 model](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/README.md)

To start with we would like to see if there a way to make any cross-over where activity comes from the c302 model and comes out in the Sibernetic model.

Pre-requisites:

- [ ] Build Sibernetic [installation instructions](http://openworm.github.io/Smoothed-Particle-Hydrodynamics/) and verify that it runs for you
- [ ] Download, install the components for and run the [c302 project](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/README.md)
- [ ] Get an understanding of how the [sinusoidal input makes it into Sibernetic](https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/master/src/main_sim.py#L25)
- [ ] Try changing the sinusoidal input directly and observing if you can make a difference when running Sibernetic
- [ ] Try making a change to the execution of [c302](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302) and observing if the graph changes
- [ ] Identify how to pull the numbers going into the c302 graph into a python variable / list / array
- [ ] Try to connect the numbers from the c302 graph into the Sibernetic python script (start not doing it in real time -- saving the numbers from one run into [a pickle file](https://docs.python.org/2/library/pickle.html) maybe
- [ ] If that works, try creating a new script that crosses over c302 with the Sibernetic python script for real time connectivity.

**Comment by slarson** [comment]
One easy way to check out Sibernetic running is to use the docker image here: hub.docker.com/r/openworm/openworm_test/

**Comment by slarson** [comment]
From @dillman:
>Sibernetic:
I've toyed around with this a bit and have been modifying the inputs for the muscle activation variables. I understand that it uses a Python object (which gets its inputs from a .dat file) to specify the level of muscle activation.

[...]

>c302:
>I've done some playing with this item and my brief understanding of how the .dat files (which I believe are the output that we need) get generated.
> 1. c302.py is run and uses various libraries to generate a Neurological Model (scaffolding only).
> 2. This neurological model is formatted and written to a *.nml file.
> 3. An appropriate LEMS.xml file is written so that jNeuroML can interpret the results.
> 4. Upon running 'pynml' a jNeuroML program is invoked which is the program that actually runs the simulation. This simulation (in real time) writes to the .dat file giving the values of each neuron at a given time.

>Queries
>If my assumptions are correct, in order to get real time output - you would need to monkey patch the jNeuroML library to direct it's output elsewhere. It looks like it would be possible to do some IPC between jNeuroML and sibernetic.
>If the plan would be to do some IPC, I think the big question that comes up is synchronization. In practice, the simulation would only be able to run as fast as either the neurological output can be generated or the physical simulation can be updated.

cc: @pgleeson @gidili @tarelli @skhayrulin @a-palyanov 

I'm not sure that "monkey patching" of jNeuroML is needed, but this question is really gets at the heart of the question of what strategy we really want to adopt here, guys.  I'm curious for folks' opinions.

The first level approach I was advocating in this issue was to just see if we can do a "replay" of activation values from c302 motor neurons into the muscles, without getting into the synchronization question.  That was because several problems that we would need to solve anyway would be addressed.  One major one is just to have a bit of code written that would compute muscle activations from the appropriate motor neuron activations.

But the next level gets to the meat of our scientific goals in the project.  It is probably time to take stock between a path that would potentially use [the Sibernetic-NEURON bridge](https://github.com/openworm/sibernetic_neuron), OR, if we think we are going to be ready soon to use [the Geppetto approach](https://github.com/openworm/org.geppetto.simulator.sph/issues/36), in which the worm body model is run in Geppetto's SPH module version of Sibernetic.  

I'm excited to see which way could be the first to meet this goal!

**Comment by tessbianchi** [comment]
I put the output of the c302 model into the Sibernetic model, in non real time. However I wanted to know if this was the correct approach to convert the cell's potential to muscle contraction:

I ran the numbers in the c302_A_Full.muscles.dat file through a sigmoid function where if the potential is -.07 (resting) or below, it returns 0 and the muscle doesn't contract. And if the potential is a -.06 it return 1 and the muscle does contract.

If this accurately reflects reality, then I can submit a PR. If not, would someone point me in the right direction of research paper that I could read on the subject.

Thanks!

**Comment by slarson** [comment]
@tessbianchi That sounds like a reasonable approximation!  At this point, that's the most we were hoping for; because the more biophysically realistic transformation would be to run the electrical activations of the motor neurons through the muscle model, and turn those into activations.  Probably the one thing to check would just be how wide is your sigmoid; as in when it sees a potential above the threshold, how long does the muscle contract for?  That width maybe should be configurable, and should probably be in proportion to the width of firing, maybe equal to 10 times the width of the "firing".  

Either way I think you should submit a PR because it sounds like what you have is a strong starting point.  We can modify / iterate from there.

**Comment by pgleeson** [comment]
@tessbianchi  @slarson The original version of the C302Simulation class (latest version here: https://github.com/pgleeson/sibernetic/blob/development/src/main_sim.py) takes the output from c302 for the "activity" (parameters B/C/C1) of the muscle cells and feeds this to sibernetic. The activity corresponds to calcium concentration (scaled to values 0->1; params C, C1) or some time averaged value of neuron firing (0->1, params B). See here for more: https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/summary/README.md.

I'd consider this activity measure better to feed to the muscles in sibernetic than the voltage, as it will be the calcium level that will ultimately influence contraction. 

Regarding feedback from sibernetic to the running simulation (as mentioned by @dillman), it's unlikely there will be a simple solution for this with jNeuroML. More likely the Neuron python code generated by jNeuroML (see here: https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/neuron_interaction/LEMS_c302_C1_Syns_nrn.py) could be adapted to allow realtime interaction/stepping through simulations/insertion of values from sibernetic. I've just started looking into this, and need to look at the Sibernetic-NEURON bridge in more detail too.

**Comment by tessbianchi** [comment]
Ok, thanks for letting me know! I was wondering what the values in c302_B_Muscles.muscles.activity.dat were.

Also, I've been looking into the Sibernetic-NEURON Bridge and I see how it displaying the data that would be fed to Sibernetic, but I don't understand how it is actually feeding the data into Sibernetic. Is this a part that still needs to be written? @skhayrulin

**Comment by tessbianchi** [comment]
I've looked at the Sibernetic-NEURON bridge, and I wasn't sure how it was to be integrated into sibernetic. So what I've done is created a folder in the source that is modeled after the sibernetic-NEURON bridge that can be used for now as a realtime way to run the c302 simulation and input it into Sibernetic. 

I think the problem with this is that there is some ovelapping source code between the two projects, but what I think we can do, is use this code for now so that we can test different c302 input. Then when the sibernetic-NEURON bridge is done, make it a dependency of this project and use that instead of the code that is here.

Also, I created a g2.2xlarge ec2 image with sibernetic setup on it, I got a 5 times speed up when running the worm (although on my computer I only get .9 FPS). The link and howto is in the readme below.

Here is the [readme](https://github.com/tessbianchi/sibernetic/tree/c302_realtime/src/c302_realtime) for setup. Please give me feedback, and then I will submit a PR.

**Comment by slarson** [comment]
Between [@tessbianchi's pull request](https://github.com/openworm/sibernetic/pull/104) and @pgleeson's work at https://github.com/pgleeson/sibernetic/tree/development (especially [sibernetic_c302.py](https://github.com/pgleeson/sibernetic/blob/14f1fe3e75de5e99c2ad99272835539792014382/sibernetic_c302.py) and [main_sim.py](https://github.com/pgleeson/sibernetic/blob/14f1fe3e75de5e99c2ad99272835539792014382/src/main_sim.py), this is now complete.  We had a good session to discuss ([notes here](https://docs.google.com/document/d/1DllO7eyC3v3QuJovMZptcdAGeUXNY4Dy0WU8BXNg-GY/edit#))

Further steps now will focus on:

1. Improving the ability for everyone to understand what is there now (updating document), using it as a foundation to build on.
2. Tuning the c302-C1 version to produce the target output we want in the muscle cells
3. Building out the realtime c302-Sibernetic bridge so we can eventually incorporate sensory feedback and creating the appropriate infrastructure to run multiple tests on HPC architectures.

cc: @skhayrulin @a-palyanov
