### ISSUE TITLE
Augment Sibernetic to send sensory feedback to Python Layer

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#178]
Currently the Sibernetic code base does not output any sensory feedback into neurons.  However, there is a [Python layer](https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/master/src/main_sim.py) that implements muscle activations.

This story is to enable mechanosensory feedback coming from the model into the Python layer so it can be integrated into a model of 302 neurons.  This means when the skin of the worm body is touched or, more generally, deformed, a signal can be received into a neuronal model.

More information about the Sibernetic code is [found in the documentation](http://docs.openworm.org/en/latest/Projects/sibernetic.html)

**Comment by slarson** [comment]
@skhayrulin @a-palyanov is this currently happening in the [sibernetic_NEURON](https://github.com/openworm/sibernetic_NEURON) repo?

**Comment by skhayrulin** [comment]
@slarson do you mean generating any sensory input and transferring it into neuron simulation? If yes than no sibernetic_NEURON making only a interface (bridge) between NEURON and Sibernetic make possible working with neuro net simulation in NEURON and transferring data into Sibernetic  directly (but in future we're planing transfer sensory data from Sibernetic into NEORUN simulation).

**Comment by slarson** [comment]
Should be a sibernetic issue going forward
