### ISSUE TITLE
Differentiation controlled by mechanical forces

### ISSUE THREAD

**Issue by StevePMcGrew** [openworm/OpenWorm#180]
The following article appears to have direct bearing on embryo development, supporting Dick Gordon's belief that mechanical forces are important in differentiation.
Steve 

 04/14/2014
Jesse Jenkins

Could human stem cells possess "long-term memories" that recall past physical environments?

The chemical environments of lab-cultured stem cells impact their differentiation in the human body, but a new study suggests that even past physical environments may dictate the future fate of a cell in what University of Colorado Boulder researchers are calling "mechanical memory." Their findings were recently published in the journal Nature Materials.

The researchers, led by University of Boulder professor Kristi Anseth, found that this "mechanical memory" may lead stem cells to differentiate into bone or fat cells based on the stiffness or softness of the substrates they were previously grown on.

To understand how the varying firmness of culture environments correlate to future cell behavior, the researchers developed a unique photodegradable material where UV light could deactivate the surface on which mesenchymal stem cells were grown—turning it from a stiff cell floor to a soft cell bed.

“We could activate or deactivate [this surface] without taking the cells off of the material, so we could really see the dosing effects on memory,” said study co-author, Mark Tibbitt, a postdoctoral fellow at Massachusetts Institute of Technology.

The longer cells were cultured in stiff environments, the higher and more prolonged the expression of RUNX2, a pre-osteogenic transcription factor,and YAP/TAZ, transcriptional co-activators involved in shuttling information from the extracellular environment. Surprisingly, after 10 days on the activated surface, cells showed irreversible RUNX2 and YAP/TAZ activation, even after retuning to a deactivated surface.

“You’d expect cells to respond to the environments that they are in, and then fade back,” said Tibbitt. “But the fact that there was a longer-term memory was really interesting.”

Now, the researchers want to know more about these stem cell memories. “One question we still have is how the cells retain their information," siad Chun Yang, Research Assistant in the Anseth Laboratory. "We have no idea how they process this signaling.”

Even so, these findings have immediate implications in the lab. “This shows that we need to carefully control the culture environment,” noted Yang. “These findings add to our understanding of how we should culture stem cells in vitro.”

Reference

Yang C, Tibbitt MW, Basta L, Anseth KS. Mechanical memory and dosing influence stem cell fate. Nat Mater. 2014 Mar 16

**Comment by slarson** [comment]
This is being worked on in https://github.com/balicea/devoworm
