### ISSUE TITLE
Thoughts on embryo modeling

### ISSUE THREAD

**Issue by StevePMcGrew** [openworm/OpenWorm#181]
Among the rules that should eventually be made available for using OpenWorm to model embryo development are:

    Cell splitting and/or differentiation triggered by:
        contact between two specific cell types
        current cell state
        cell history
        distance to other specific cell types (regardless of intervening cells)
        timing of events

    Cell migration guided by distance from other specific cell types (essentially the same as morphogen gradients)

Eventually, the model will need mechanical calculations. First will be the issue of cell packing, taking into account:

    Adhesion between different cell types (probably controlled by surface proteins)
    size of each cell type
    stiffness/deformability of each cell type

Using just those factors, it should be possible to dump a bunch of cells into a bag, shake it, and see an organism take shape.  Without the right history the shape is likely to be wrong-- but I'll bet that with some combination of those factors, with the right values plugged in, and with the right history, we can build an embryo.

**Comment by slarson** [comment]
This is being worked on in https://github.com/balicea/devoworm
