### ISSUE TITLE
Save worm features for use in Gepetto

### ISSUE THREAD

**Issue by JimHokanson** [openworm/OpenWorm#208]
We are working on saving worm features (currently in the movement validation repo) into a format that Gepetto will work with.

The recording creator class is currently at:
https://github.com/openworm/org.geppetto.recording/blob/master/org/geppetto/recording/GeppettoRecordingCreator.py

An example of using this is at:
https://github.com/openworm/org.geppetto.recording/blob/master/org/geppetto/recording/CreateTestGeppettoRecording.py

Steps required:
1) Since we currently don't have the feature processing pipeline finished, we need to finish being able to load a MRC feature file from disk
2) When all the features are in memory, save them back into the new format (using code referenced above)

Code will be placed in:
https://github.com/openworm/movement_validation/blob/master/movement_validation/features/worm_features.py

**Comment by MichaelCurrie** [comment]
I believe this is now handled by [JSON_Serializer](https://github.com/openworm/movement_validation/blob/master/movement_validation/basic_worm.py).  If we make WormFeatures inherit from this class, then the `save_to_JSON` and `load_from_JSON` methods allow the worm features to be loaded and saved.

Linking this format to the recording creator class referenced above is something that might still need to be done, but the links in the first post on this issue are now broken.  Can @tarelli or @JimHokanson give me an update?  Thanks!

**Comment by slarson** [comment]
Should be moved to the appropriate geppetto repo.  Closing for now.
