### ISSUE TITLE
Modeling a decision making circuit

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#212]
In [a paper by Cori Bargman](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2760495/) a social behavior in _C. elegans_ is analyzed down to the level of its underlying circuit.  The putative circuit appears to be the following:

![screen shot 2014-07-20 at 11 03 46 pm](https://cloud.githubusercontent.com/assets/1037756/3743860/5365ed4e-1781-11e4-8a78-367daccefed0.png)

We're working to explore what we know about this circuit already and to use this exploration to help improve the tools around the project.

First stop, PyOpenWorm.  Can we pull out the circuit from it?

```
RMG neuron info:
type: interneuron
receptors: []


URX neuron info:
type: sensoryinterneuron
receptors: ['SRA-10', 'GCY-1', 'GCY-32', 'GCY-35', 'GCY-34', 'GCY-36', 'GCY-37', 'GCY-25', 'NPR-1']

ASK neuron info:
type: sensory
receptors: ['OSM-9', 'DAF-11', 'SRA-9', 'SRG-2', 'SRA-7', 'SRG-8']

ASJ neuron info:
type: sensory
receptors: ['DAF-11', 'SRE-1', 'OSM-9']

Do nodes exist? (RMGR,URXR,ASKR,ASJR)
True
True
True
True
Do edges exist? (RMGR/URXR, RMGR/ASKR, RMGR/ASJR, URXR/ASKR, URXR/ASJR, ASKR,ASJR)
True
True
False
False
False
False
Get edge info
{'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
{'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}

Get edge info
"RMGR", "URXR": {'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
"RMGR", "ASKR": {'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
"RMGR", "ASJR": None
"RMGR", "RMHR": {'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
"RMGR", "AWBR": {'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
"RMGR", "IL2R": {'synapse': 'GapJunction', 'neurotransmitter': 'FRMFemide_GJ', 'weight': '1'}
"RMGR", "ASHR": {'synapse': 'Send', 'neurotransmitter': 'FRMFemide', 'weight': '1'}
"RMGR", "ADLR": None
```

Close, but not quite.  Next step here is to [improve the DB](https://github.com/openworm/PyOpenWorm/issues/25)

In addition, we could be testing out how this particular circuit is currently working in the [c302 model](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302), to sanity check the connections.  We could run the c302 model such that we check out all the edges in this network to see if they produce output that makes sense given the connections that exist.  For example, are chemical synapse connections unidirectional?  Are gap junctions bi-directional?

**Comment by slarson** [comment]
@pgleeson -- @aribrich and I are trying to remember if NeuroML2 has added support for gap junctions yet.  I have a vague recollection you may have done this, but can't find where this may have happened.  We got back to wondering about this again.

**Comment by slarson** [comment]
@pgleeson OK we have located the [example gap junctions NML file in the development branch here](https://github.com/NeuroML/NeuroML2/blob/development/examples/NML2_GapJunctions.nml).  We've also noted this issue: NeuroML/NeuroML2#34.  We'd like to help if possible.

**Comment by slarson** [comment]
@pgleeson also referencing this issue LEMS/jLEMS#31 as we realize this is also key to making this happen.

**Comment by slarson** [comment]
I'm recommending that @aribrich try out the experimental jLEMS branch as recommended in [this comment](https://github.com/LEMS/jLEMS/issues/31#issuecomment-60735126) and report back on the state of gap junction support.

**Comment by slarson** [comment]
@portegys -- you were also interested in this issue.  Do you want to try checking out this branch as well?

**Comment by portegys** [comment]
Sounds good in a couple of days.

**Comment by pgleeson** [comment]
Yes, gap junction support is there now in the development branches of NML2/LEMS and the c302 examples with gjs (e.g. https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/c302_B_Social.nml) should work with this.

**Comment by slarson** [comment]
@brijeshmodi12 have a look at this

**Comment by brijeshmodi12** [comment]
@slarson 
Plots after executing runAndPlot.py 

![ca2 _of_6_cells](https://cloud.githubusercontent.com/assets/17252806/16742333/da153668-47c4-11e6-92fb-d9dc8c8008bb.png)
![membrane_potentials_of_6_cells](https://cloud.githubusercontent.com/assets/17252806/16742332/da12e5ac-47c4-11e6-9e00-a5a00f90df1a.png)

**Comment by brijeshmodi12** [comment]
@slarson 

After reading padriag's comment, I think the following should be the next steps:

1. Since the behavior of cells is not realistic, we can model each cell individually and how they fire. If I am not wrong, the cells in C ELegans social circuit don't integrate and fire. Do they?

2. Employing Gap junctions wherever required, instead of chemical synapse.
Do we know how each cell is generating its output? Any paper describing that? or other source of info which we follow generally?

**Comment by slarson** [comment]
@brijeshmodi12 We are currently working with a model of the neurons that is defined by hodgkin huxley equations as described here: https://hodgkin-huxley-tutorial.readthedocs.io/en/latest/  Instead.  The key there is to pick appropriate channels :)  

So how do we do that?  Good question.  We have another project [ChannelWorm](https://github.com/openworm/channelworm) where we are aggregating information about channel models.  

On your second point; we do need to make sure the gap junctions are present in the model.  Are you able to run it?

**Comment by slarson** [comment]
This largely happened as in incorporated into c302.  Much more to be done but this was a great start.
