### ISSUE TITLE
3d eigenworm visualisation

### ISSUE THREAD

**Issue by balazs1987** [openworm/OpenWorm#215]
I want to visualize worms in 3d based on eigenworms. The idea is that we input an eigenworm time series and the corresponding 3d movie of the worm comes out.

**Comment by slarson** [comment]
@balazs1987 I wonder if the work being done to create the collada animation of the worm would be helpful here.  That collada animation should be importable into Blender, and then its joints would be scriptable.  You can read more about this animation technique here: https://en.wikipedia.org/wiki/Skeletal_animation
