### ISSUE TITLE
Review Integration diagram

### ISSUE THREAD

**Issue by tarelli** [openworm/OpenWorm#217]
I created a diagram to put together all the different efforts that are ongoing in the same picture and connect them showing a division between data and processes.
![Diagram](https://www.lucidchart.com/publicSegments/view/54edf05c-71b8-4086-9a0c-5a050a004805/image.png)
Any comments are welcome, the diagram is also available for editing [here](https://www.lucidchart.com/documents/edit/832c1c53-2840-421f-9546-01499bb9c753/0).

**Comment by rgerkin** [comment]
Very cool.  What about muscle model validation (in addition to movement validation)?  Or maybe validation is implied at every step and is redundant?

**Comment by tarelli** [comment]
Thanks Rich, I think it's a good point, I'll make it explicit.

**Comment by tarelli** [comment]
Updated revision of the integration diagram, thanks @slarson and @travs for the input!

![openworm integration - neuromechanical simulation](https://cloud.githubusercontent.com/assets/81127/8682534/6f646e6a-2a65-11e5-8c26-0cb26d53ccd9.png)

**Comment by cheelee** [comment]
Quick question - is there a way to create some form of a marked-up version of the image so users could click on the various components, and it'd bring them to the appropriate github repository?

**Comment by tarelli** [comment]
@cheelee great idea, I'll work on it
