### ISSUE TITLE
OpenWorm app missing from US App Store

### ISSUE THREAD

**Issue by maccaches** [openworm/OpenWorm#221]
I get the following error when attempting to install OpenWorm on my iPhone:

> Item Not Available
> 
> The item you've requested is not currently available in the U.S. store.

**Comment by slarson** [comment]
We'll look into this.  Thanks for reporting!

cc: @gidili @tarelli

**Comment by slarson** [comment]
We had a discussion about this and for now we are going to deprecate the iphone app.  However, you can always check out the web version at http://browser.openworm.org.  We are updating the website to reflect this.
