### ISSUE TITLE
Start running experiments with the muscle+motor neuron system of c302

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#224]
There has been a proposal to create a directory structure where the outputs of both c302 and Sibernetic would go, where we could also version different runs of the simulations.  I'll try to dig up this proposal and then we can begin to iterate on it.

**Comment by pgleeson** [comment]
All of this functionality is here: https://github.com/pgleeson/sibernetic/tree/development; needs a clean up & docs...

**Comment by slarson** [comment]
This has now happened
