### ISSUE TITLE
Construct the tap-withdrawal circuit within c302

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#225]

**Comment by slarson** [comment]
@pgleeson requesting that we start collaborating on a google doc that defines the tap withdrawal circuit in detail.  Let's be sure to link it here into this issue.

**Comment by slarson** [comment]
Notes from today's meeting with @raminmh and @lungd:

* Connectome data for the circuit was old -- updated them based on tap withdrawal connectivity.
* Used a different set of parameters for a graded potential
* Got behavior that was closer to what was expected from AVM - AVA cells, PLM - AVB
* May be that inhibition is too weak because all cells are being excited, whereas the correct behavior is that AVA should go down.

Work still ongoing with changing conductances to make the behavior correct.

**Comment by lungd** [comment]
I need to do some fine-tuning but I almost get the correct output.

- Separate activation of PLM and AVM
    - Input current of 5pA
      ![c302_twc_5pa](https://cloud.githubusercontent.com/assets/5890526/20797634/f9e13a78-b7db-11e6-9f7a-7a283912ec2b.png)

    - 14pA
![c302_twc_14pa](https://cloud.githubusercontent.com/assets/5890526/20797669/1bc9e89c-b7dc-11e6-882c-6fe24c6ff38f.png)
 

- Simultaneous activation
    - 5pA
![c302_twc_5pa](https://cloud.githubusercontent.com/assets/5890526/20797806/bec5f86a-b7dc-11e6-87a0-34ace0d12da1.png)

    - 14pA
![c302_twc_14pa](https://cloud.githubusercontent.com/assets/5890526/20797812/c502d87e-b7dc-11e6-8918-d87c1cfc5be2.png)

    - PLM:5pA, AVM:14pA
![c302_twc_plm-5pa_avm-14pa](https://cloud.githubusercontent.com/assets/5890526/20797823/ccab8ba2-b7dc-11e6-9a73-e565f36b75fc.png)

    - PLM:14pA, AVM:5pA
![c302_twc_plm-14pa_avm-5pa](https://cloud.githubusercontent.com/assets/5890526/20797828/d122c920-b7dc-11e6-859c-6273dfea7fb2.png)

**Comment by slarson** [comment]
Brilliant. Ready for a pull request?

**Comment by lungd** [comment]
Let me edit/check my parameters a bit longer. I think I'll create a PR tomorrow or monday at the latest...

**Comment by pgleeson** [comment]
@lungd Looks good. Please merge in the recent changes to master before opening the PR. Also, can you make it so the use of your updated spreadsheet reader is an optional setting in c302.py, not the default, or all the existing generated networks will change. Thanks!

**Comment by lungd** [comment]
@pgleeson (@slarson)  do you want me to create a PR for my c302.py changes first?
* Add param to override the polarity of connections.
* Override conn number of GJ with "A-B_GJ". It wasn't possible to override the conn number of a chem-syn. and an elec-syn with the same pre and post syn. separately?

**Comment by slarson** [comment]
@lungd I think @pgleeson is saying to make sure you pull in his most recent changes he has made on the master branch and merge them in to your fork before you make the PR.  [This page](https://help.github.com/articles/syncing-a-fork/) should explain how to get the new changes in; then it will be up to you to do the merge where there may be any conflicts.

**Comment by lungd** [comment]
I was thinking about creating a PR only with the c302 changes I mentioned above, merging them into my fork after you have accepted and merged them into the original openworm project so I can create a PR only for the TW circuit (c302_TW and params file).
I can also create a single PR with all the changes. As you like.

**Comment by pgleeson** [comment]
@lungd yes, it would be great if you could create a PR with just the main changes to c302.py etc. so these can be checked through, and then you can add one for the tap circuit.

**Comment by lungd** [comment]
First part: https://github.com/openworm/CElegansNeuroML/pull/74.

**Comment by slarson** [comment]
It was constructed.  Future issues will focus on tuning it.
