### ISSUE TITLE
Sibernetic needs to output worm contour points

### ISSUE THREAD

**Issue by gidili** [openworm/OpenWorm#246]
Being tracked at the repository level here: https://github.com/openworm/sibernetic/issues/119

**Comment by gidili** [comment]
Was this actual done and integrated into the [conversion script](https://github.com/openworm/tracker-commons/pull/149) you wrote @pgleeson ?

cc: @a-palyanov

**Comment by MichaelCurrie** [comment]
WCON specification does allow this now.  https://github.com/openworm/tracker-commons/issues/132

**Comment by pgleeson** [comment]
This is the main issue for Sibernetic related to the output of contours: https://github.com/openworm/sibernetic/issues/119.

As far as I can see, @a-palyanov's code for outputting these points to txt file has not yet been merged into development (or put on github). @skhayrulin can you confirm?

**Comment by slarson** [comment]
Closed by #247
