### ISSUE TITLE
WCON model interpreter for Geppetto so we can visualize Sibernetic/Movement validation recordings

### ISSUE THREAD

**Issue by gidili** [openworm/OpenWorm#248]

**Comment by MichaelCurrie** [comment]
We've been working this month on a "WCON Viewer" in d3.js which will let us view recordings in the WCON format at movement.openworm.org.

I believe the workflow will be for Sibernetic to convert its output to WCON via @pgleeson's conversion script, https://github.com/openworm/tracker-commons/pull/149, and then this WCON file can be passed via POST request to the movement.openworm.org Django server hosted on AWS.  It will add the Sibernetic WCON recording to our mysql database.  The features will be automatically calculated after the POST request.

Then the recording can be viewed in the WCON viewer, and the resulting feature vector will be projected down to two dimensions and potted in a scatterplot at the [OpenWorm Dashboard](https://github.com/openworm/movement_cloud/issues/83).

So I actually think we can mark this as "WONTFIX" for now.  But please correct me if I am wrong and if there is the will to implement this as a Geppetto widget.

**Comment by tarelli** [comment]
@MichaelCurrie last time we talked about this we said that we would wrap it once you guys were done. Can you point to the code for the D3? Thanks.

**Comment by cheelee** [comment]
@tarelli Hi Matteo - try this. It just needs to be started with python3 http.server. https://github.com/openworm/movement_cloud/tree/dev/WCON_viewer

**Comment by tarelli** [comment]
Thanks @cheelee 👍 
<img width="549" alt="screen shot 2017-06-15 at 18 08 42" src="https://user-images.githubusercontent.com/81127/27193123-b187b69e-51f5-11e7-95fa-15b6afadeb11.png">
