### ISSUE TITLE
Once release 0.1 works, submit PRs to all repos & point to released versions in final 0.1 version

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#251]
Request PRs:
- [x] https://github.com/lungd/pyNeuroML - branch ow-0.1
- [x] https://github.com/lungd/CElegansNeuroML branch ow-0.1
- [x] https://github.com/lungd/sibernetic branch ow-0.1

Get PRs merged:
- [x] https://github.com/NeuroML/pyNeuroML/pull/52
- [ ] https://github.com/openworm/CElegansNeuroML/pull/102
- [x] https://github.com/openworm/sibernetic/pull/138

Incorporate merged or specific commit versions into Dockerfile & test:
- [x] PyOpenWorm
- [x] jNeuroML
- [x] nrn
- [x] iv
- [x] pyNeuroML
- [x] CElegansNeuroML
- [x] sibernetic

**Comment by slarson** [comment]
In progress in development branch

**Comment by pgleeson** [comment]
Out of date...
