### ISSUE TITLE
Incorporate faster Sibernetic

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#256]
Testing the performance improved version of Sibernetic out to see if it makes a difference:

https://github.com/openworm/sibernetic/compare/64284551e997...faf5a99f3cc3

This would be complete if the faster version is incorporated, or if we rule out that it cannot be used.

**Comment by lungd** [comment]
https://github.com/openworm/sibernetic/pull/157

**Comment by pgleeson** [comment]
Done
