### ISSUE TITLE
Define the Physiology of each Neuropeptide for each given Neuron

### ISSUE THREAD

**Issue by Interintel** [openworm/OpenWorm#29]
Document how the Neuropeptide is used by the Neuron and the effects of changes that the Neuropeptide expresses. Initially we will create this in a spreadsheet but the end result of data storage is to be determined based on the complexity of what we find.

**Comment by slarson** [comment]
Neuropeptides are now in PyOpenWorm.  How to incorporate them into c302 will be a topic for that repo going forward
