### ISSUE TITLE
Release 0.8: Documentation issues.

### ISSUE THREAD

**Issue by cheelee** [openworm/OpenWorm#298]
On Mac OS X 10.15.2:

1. The documentation omits instructions to have the Docker daemon running before executing run.sh; and
2. The documentation has instructions for the user to invoke “exit” and “stop.sh” after successful completion of the test run. I believe this is already integrated into run.sh and no longer relevant;

**Comment by pgleeson** [comment]
@cheelee 
1. Good point. Clarified in https://github.com/openworm/OpenWorm/commit/7cc8ec20caae04ebbfc930fe0db9eee50aa765d4, also for Windows
2. Yes. This should be clearer now in the Readme.
