### ISSUE TITLE
Release 0.8: Corrupted video.

### ISSUE THREAD

**Issue by cheelee** [openworm/OpenWorm#299]
On Mac OS X 10.15.2:

After making a test run as outlined in documentation, in the output folder for file cut_C2_FW_yyyy-mm-dd_hh-mm-ss.mp4, the video is corrupted and looks like this throughout its display time.

Screenshot:
<img width="1195" alt="Screenshot 2020-01-10 at 12 54 58 PM" src="https://user-images.githubusercontent.com/316749/72126867-b73d6d80-33a8-11ea-9d6b-57c2203b50c1.png">

Corrupted file itself:
[cut_C2_FW_2020-01-10_04-05-36.mp4.zip](https://github.com/openworm/OpenWorm/files/4044002/cut_C2_FW_2020-01-10_04-05-36.mp4.zip)

**Comment by pgleeson** [comment]
I'm seeing this too in the development branch. However 3 mp4 files are produced and the main one does work, e.g.

C2_FW_2020-02-19_18-10-28.mp4                            <- displays fine
speeded_C2_FW_2020-02-19_18-10-28.mp4      <- corrupted
cut_C2_FW_2020-02-19_18-10-28.mp4            <- corrupted

**Comment by pgleeson** [comment]
@cheelee I've tested this with the latest py3 version (just merged to master) on Mac Big Sur and Ubuntu and the videos are no longer corrupted (although the mp4 files don't play with QuickTime, but do with VLC).
Closing, but if you have a chance to recheck with the latest version it would be great.

**Comment by cheelee** [comment]
@pgleeson That's great! I just tested this on my MacMini with clean Docker images and it works like you had indicated. All the associated PNG files look good and the WCON file generated also works with our little visualizer on the Movement Cloud web tool, so things are looking great!

Thanks for taking care of this!

**Comment by pgleeson** [comment]
@cheelee Great news, thanks for testing!
