### ISSUE TITLE
Connect with Hemibrain

### ISSUE THREAD

**Issue by 0wnrepo** [openworm/OpenWorm#300]
Hi, these guys just mapped the connectome of a fly Drosophila melanogaster: 
https://www.janelia.org/project-team/flyem/hemibrain
https://www.wired.com/story/most-complete-brain-map-ever-is-here-a-flys-connectome/
https://ai.googleblog.com/2020/01/releasing-drosophila-hemibrain.html

Maybe team up? Or learn / import some of their data.
Regards

**Comment by Sayanta66** [comment]
Can I work on this project?

**Comment by mwatts15** [comment]
@0wnrepo We could do something with it at some point, but at the moment it really seems out of scope for OpenWorm. So, I'm going to close this.
@Sayanta66 If you mean OpenWorm generally, yeah, for sure. I have some doubts about what would be done with the Drosophila connectome, but you can join us on Slack to discuss.
@cheelee @tarelli @balicea Do you have have a Slack invite link? I can only invite people by email it seems.

**Comment by mwatts15** [comment]
@Sayanta66 you can join Slack from here https://launchpass.com/openworm
