### ISSUE TITLE
Remove xubuntu-desktop installation

### ISSUE THREAD

**Issue by mwatts15** [openworm/OpenWorm#303]
Currently we are installing xubuntu-desktop Apt package in the docker image. This shouldn't be necessary since the docker image isn't providing a desktop environment. The installation of xubuntu-desktop should be removed and then the docker image can be rebuilt. Any failures that result from this can be handled by adding back any dependencies of xubuntu-desktop package that are actually needed to run.

**Comment by pgleeson** [comment]
This has been removed in both the python2 and python 3 versions in the development branch and both seem to be working... Testing appreciated.

**Comment by clausagerskov** [comment]
[output2.log](https://github.com/openworm/OpenWorm/files/5299548/output2.log)
Ran build.cmd on Docker in Windows 10 x64 Pro with following output.
Had to modify the DISPLAY variable to get a graphics window.
doesn't seem to produce an mp4 though.

**Comment by clausagerskov** [comment]
works fine on Ubuntu 20.04 with Docker engine 
[run.log](https://github.com/openworm/OpenWorm/files/5300214/run.log)

**Comment by clausagerskov** [comment]
error with ffmpeg in Windows is probably from me messing with the DISPLAY var

**Comment by pgleeson** [comment]
Great to hear. Thanks for testing @clausagerskov!

**Comment by clausagerskov** [comment]
Yep as I suspected, outputs videos with no problem on Windows if I don't mess with the master_openworm.py file

**Comment by pgleeson** [comment]
No longer installed in py3 dockerfile
