### ISSUE TITLE
Find ion channels that relate to motor neurons AS01, AS02, DA01, DA02, DB01, DD01, SMDDL, SMDDR

### ISSUE THREAD

**Issue by Interintel** [openworm/OpenWorm#31]
Define the specific types of Ion Channels and how they work within the cell.

[Here's a powerpoint presentation](https://www.dropbox.com/s/766uv7dbi4d9ojw/Open%20Worm%20Journal%20Club%202.ppt) that explains what ion channels are and some of the math behind simulating them.

[Here's a book](https://www.dropbox.com/s/7z7f3hrpkivmyjl/Bertil_Hille-Ionic_Channels_of_Excitable_Membranes%2C_Sinauer_Associates_Inc%281992%29.pdf) explaining what ion channels are, and how they relate to neurons.

[This spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdEd6S0dfVnE4blhaY2ZIWDBvZFNjT0E#gid=0) contains a very early documenting of ion channels in muscle cells, but begins to lay out the way in which we should start describing them.  

[Gene expression patterns](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdEd6S0dfVnE4blhaY2ZIWDBvZFNjT0E#gid=1) that can be used to infer the location of ion channels are in another sheet in that same spreadsheet.

[Here's a list](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdGxUeGljZjktYUJoZkU0V0IwMDhIZ0E#gid=5) of neurotransmitter receptors and what neurotransmitters they receive.

A wealth of neurotransmitter receptors are described on [https://docs.google.com/spreadsheet/ccc?key=0ArNOKkIblIRadE5lVkN4WGMzNUZLdVROUEZVTUlUVGc#gid=0](this spreadsheet), maintained by Z.F. Altun.

[Textpresso for c elegans](http://www.textpresso.org/celegans/) provides full text search of c. elegans journal articles and can be used to find papers that talk about specific ion channel types.

**Comment by slarson** [comment]
@Linuxese --thanks for agreeing to look into c. elegans RNASeq data.  We also talked about looking into c. elegans ion channel mutants -- maybe we can try this as a next step.  Could you update us here on any progress that you make?

**Comment by slarson** [comment]
@VahidGh is working on the following: 

```
Right now, I'm working on studies related to ion channels underlying current in NMJ, studies are more related to body wall muscle than motor neurons.
In brief, important genes from the spread sheet are: egl-19, SHK-1, SLO-1, SHL-1, and CCA-1, and UNC-36 in muscle cells, and UNC-2, SLO-1, SLO-2, and SHK-1 for motor neurons.
(I'm working on a document with detailed info and refs)
```

**Comment by slarson** [comment]
Adding my update I typed up earlier:

As many channels as we can infer that are in the motor neurons (AS01, AS02, DA01, DA02, DB01, DD01, SMDDL, SMDDR), models for the synapses between these and our muscle cell, and the muscle cell itself. So @ahrasheed -- your efforts to get the motor neurons LEMS files generated then creates a rallying point for these ion channels to be attached. @VahidGh and @wilzh40 if we can start sorting the ion channel spreadsheet for those ion channels that either reference those neurons by name or has the word "motor" or possibly "ventral cord" or "dorsal cord" neurons since those neurons go through there, then we can start to build up a better list of ion channels to pursue. Make sense, all?

**Comment by slarson** [comment]
I've added columns L-T to [the spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Avt3mQaA-HaMdEd6S0dfVnE4blhaY2ZIWDBvZFNjT0E#gid=1) to sort out specifically which ion channels we can infer are in which cells.  If I've marked YES, the cell has been called out by name in a specific paper as having that ion channel expressed.  In the case of the body wall muscle cell, I don't use the standard of called out by name for a YES, instead just if it says it is expressed in "body wall muscle" without qualifications.  If I've marked Maybe, the cell is called out as being a member of either the ventral cord neurons or the ring neurons.  If I've marked Maybe-weak, it is a member of the class but someone said expression was weak.

Here are the ion channels of most interest for the motor neurons (marked YES for at least some):

LGC-46, TRP-1, LGC-55, GLR-1, UNC-8, ACC-4

Next priority, those marked Maybe or Maybe-Weak for at least some:

CLH-2, SLO-1, SLO-2, UNC-36, SHL-1, TWK-20, CCA-1, AVR-14, EGL-2, EXP-2, GLC-3, GLC-4, TAX-4, AVR-15, KVS-1, MOD-1

Although the spreadsheet was focused on looking for ion channels for neurons, not muscles, the following came out as YES for body wall muscle:

CLH-2, SLO-1, SLO-2, UNC-36, LGC-46, SHL-1, SUP-9, SHK-1, LGC-34

an these as Maybe for body wall muscle:

TWK-20, CCA-1, DEG-1

**Comment by VahidGh** [comment]
@slarson, according to [this new study](http://www.mendeley.com/c/7530171114/g/835901/liu-2014-slo-2-potassium-channel-is-an-important-regulator-of-neurotransmitter-release-in-caenorhabditis-elegans/), this is the only study with voltage/current clamp data available for motor neurons (the study is based-on VA5, VB6 and VD5 motor neurons):
* "To our knowledge, there has been no report on whole-cell voltage- and current-clamp recordings from C. elegans motor neurons. In the present study, we successfully performed electrophysiological recordings of motor neurons, and combined the electrophysiological data with PSCs recorded from body-wall muscle cells to assess physiological roles of SLO-2 in motor neurons. Our results suggest that SLO-2 is a major contributor to delayed outward current in motor neurons with its activity dependent on Ca2+ entry through a L-type voltage-gated Ca2+ channel (VGCC), and that SLO-2 controls the strength of synaptic transmission by regulating the duration and charge transfer rate of PSC bursts, which are used by motor neurons to control body-wall muscle."
* "Observations suggest that delayed outward current of VA5 and VB6 results primarily from SLO-2 with a small contribution from an unidentified channel(s), whereas that of VD5 results almost completely from SHK-1 and SLO-2"
* "While SLO-1 is localized at the presynaptic site and is likely regulated by Ca2+ entry through UNC-2, which is also localized at the presynaptic site, SLO-2 might be localized to other subcellular domains and coupled to Ca2+ entry through EGL-19."

**Comment by slarson** [comment]
@VahidGh This is a great find!  It looks like the [Wang Lab](http://zwwang.uchc.edu/publications/index.html) has many relevant publications for us.

**Comment by VahidGh** [comment]
@slarson, unfortunately, the paper is more focused on the genetic part and lacking data related to their patch clamp experiment. 
It would be great if we could have their raw data.

**Comment by slarson** [comment]
What about the I/V curves in Figures 1 & 5.  What additional data would we
want?  We can always email the authors, but we should figure out
specifically what we would want.

**Comment by VahidGh** [comment]
yes, but it's not enough for the fitting (especially activation/inactivation expressions).
according to the paper: "Current- and voltage-clamp experiments were performed with a Multiclamp 700B amplifier (Molecular Devices, Sunnyvale, CA, USA) and the Clampex software (version 10, Molecular Devices)."
So if we could have Axon abf/atf files, we could simulate and analyze the experiment more accurate and easier.

**Comment by slarson** [comment]
This effort has spun off into the https://github.com/openworm/channelworm repository
