### ISSUE TITLE
Cannot Join Slack Channel

### ISSUE THREAD

**Issue by TC-Wheel** [openworm/OpenWorm#319]
I filled out the survey here: 
https://badgelist.com/OpenWorm/Plugged-In/Join-our-Slack-channel
which gave me the link:
https://launchpass.com/openworm 
which fails to send me an invite. 

The email I entered is from Gmail, and is associated with Slack already. 
I made a video showing the issue in case that helps.

https://user-images.githubusercontent.com/96085470/150891400-852b6f55-5ea9-4178-9338-c359419fbd13.mp4

I still love you all- I just want to express that via Slack.

**Comment by pgleeson** [comment]
@TC-Wheel I've just tried that at https://launchpass.com/openworm and got the email invite immediately. Have you checked your spam filter for an email with subject "Stephen Larson has invited you to work with them in Slack"?

**Comment by chirag1701** [comment]
HI , I am facing the same issue !! 
I have tried with 2 different emails but i am not getting the invite.

**Comment by pgleeson** [comment]
Sorry you were having problems @chirag1701. Send me your email and I'll add you manually:https://openneuroai.org/contact

**Comment by chirag1701** [comment]
Thanks ! I have mailed you @pgleeson .
