### ISSUE TITLE
docker image isn't showing

### ISSUE THREAD

**Issue by HussainAther** [openworm/OpenWorm#342]
If this issue is intended to be a *bug report*, please fill out the following:

**Expected behavior**
Image should be viewed

**Actual behavior**
Any idea what could be causing this error?
(devoworm) syedather@Syeds-MBP-2 OpenWorm % docker scout quickview openworm/openworm
  i New version 1.4.1 available (installed version is 1.3.0) at https://github.com/docker/scout-cli
  ⠇ Storing image for indexing%                        (devoworm) syedather@Syeds-MBP-2 OpenWorm % docker scout quickview openworm/openworm
  i New version 1.4.1 available (installed version is 1.3.0) at https://github.com/docker/scout-cli
ERROR   Status: could not get the image openworm/openworm from cache: failed to copy image: failed to create new image source: unable to load image: could not read image: open /var/folders/2g/mg4_q7jn3qndbhzmw0pnlhg40000gn/T/docker-scout/sha256/09a2c345c50c3cc378effb46f59552b3c964366d03b2dadf4f51cdbfff92bade/b03be215-338b-4528-95b8-d9974044dd74/blobs/sha256/f4a670ac65b68f8757aea863ac0de19e627c0ea57165abad8094eae512ca7dad: no such file or directory, Code: 1
I’m currently this on my Docker image on my Macbook with an external hard ddrive (4 TB). It should have enough but it seemsl ike my Mac keeps running out of application memory. Any suggestions on best ways to run given my tehcnical limitations ?
Unfortunately I don’t have access to any large computing facilities

docker/scout-cli
Docker Scout CLI
Website
https://docker.com/products/docker-scout
Stars
161
Added by [GitHub](https://openworm.slack.com/services/B01UHKWKC6P)

**Steps to reproduce the behavior**
I’m currently this on my Docker image on my Macbook with an external hard drive (4 TB). It should have enough but it seems like my Mac keeps running out of application memory. Any suggestions on the best ways to run given my technical limitations ?

https://hub.docker.com/r/openworm/openworm

---

If this issue is intended to be a *beginner issue*, please add all of the following:

- [x] Requirements are clearly specified
- [x] Links to relevant "getting started" documentation
- [x] Tagged as "beginner"
- [x] Tagged with language skill needed to complete
- [x] Level of difficulty: Standalone
  * Trivial = Changing one-line of code somewhere.
  * Standalone = Changes & Development do not affect other components of project. Tasks can be on a critical path, but probably should not be.
  * Simple = from 2 hours work to maybe a week’s work (Thinking + Coding)

**Comment by pgleeson** [comment]
@HussainAther I've not used docker scout before, so not clear what the issues with that are.

The recommended way to use it is to clone the repo and build it locally to run as per https://github.com/openworm/OpenWorm?tab=readme-ov-file#quickstart. Did this work?

**Comment by HussainAther** [comment]
Issue has been resovled. Thanks. It came down to some memory storage issues on my hard drive. Close.
