### ISSUE TITLE
Build.cmd & Run.cmd referencing wrong version?

### ISSUE THREAD

**Issue by Daasin** [openworm/OpenWorm#345]
### Discussed in https://github.com/openworm/OpenWorm/discussions/344

<div type='discussions-op-text'>

<sup>Originally posted by **Daasin** May  3, 2024</sup>
and is there a way to get 0.9.4? Opening the files it seems to reference 0.9.4 but says 0.9.3 in windows terminal after building or running</div>

Turns out build.cmd and run.cmd both referenced the older version

**Comment by pgleeson** [comment]
Thanks for the update. It's all not very well tested on Windows unfortunately, simply because most of us work on Linux/Mac, but if you do have suggestions for improvments we're happy to incorporate them.

**Comment by Daasin** [comment]
> Thanks for the update. It's all not very well tested on Windows unfortunately, simply because most of us work on Linux/Mac, but if you do have suggestions for improvments we're happy to incorporate them.

Does it run on Docker Engine in Linux? 

And for Windows, Would love a way to utilise my GPU to accelerate it without completely passing through my GPU to the VM. Would make testing a lot faster, no? Docker Desktop seems to only have guides for NVIDIA GPU's which I found strange considering they're seen as more difficult to work with on Linux.

**Comment by Daasin** [comment]
> Thanks for the update. It's all not very well tested on Windows unfortunately, simply because most of us work on Linux/Mac, but if you do have suggestions for improvments we're happy to incorporate them.

@pgleeson Does it run on Docker Engine in Linux?

And for Windows, Would love a way to utilise my GPU to accelerate it without completely passing through my GPU to the VM. Would make testing a lot faster, no? Docker Desktop seems to only have guides for NVIDIA GPU's which I found strange considering they're seen as more difficult to work with on Linux.

**Comment by Daasin** [comment]
> Thanks for the update. It's all not very well tested on Windows unfortunately, simply because most of us work on Linux/Mac, but if you do have suggestions for improvments we're happy to incorporate them.

Also just realised the issue I faced is mirrored on #336 except it applies to 0.9.4 aswell

**Comment by ElamathiiSelvan** [comment]
shall i solve this issues

**Comment by Daasin** [comment]
> failed to find output in ow sibernetics folder, not the first time I've had that issue 

If you can solve that one which seems to happen across multiple operating systems as seen in #336 then that'd be great @ElamathiiSelvan

**Comment by Daasin** [comment]
@pgleeson Also closing this as the problem seems to be better described in the other issue

**Comment by pgleeson** [comment]
Thanks @Daasin
