### ISSUE TITLE
'hoc.HocObject' object has no attribute 'a_MVL24'

### ISSUE THREAD

**Issue by schzene** [openworm/OpenWorm#352]
I noticed this warning when run the code:

```
'hoc.HocObject' object has no attribute 'a_MVL24'
```

Will this have any impact on the running results?

**Comment by pgleeson** [comment]
Thanks for reporting @schzene. No, this won't have any impact. There is no muscle MVL24 in the real C. elegans (see https://royalsocietypublishing.org/doi/10.1098/rstb.2017.0376, there are 4 quadrants of muscles, 3 have 24 muscles the ventral left one (MVL) has 23 -> 95 total). 
The neural network generated by c302 which powers Sibernetic in this case has the correct 95 muscles, with MVL24 missing. This code: https://github.com/openworm/sibernetic/blob/development/main_sim.py#L219 just catches the error and prints it out and continues if that muscle is not found: https://github.com/openworm/sibernetic/blob/development/main_sim.py#L219.
I'll update the error message to make it clearer...

**Comment by schzene** [comment]
Thanks a lot for your reply!
