### ISSUE TITLE
Elaborate 3D physical scene data format -- input data for physics solver

### ISSUE THREAD

**Issue by a-palyanov** [openworm/OpenWorm#65]
Current state is inconvenient and unsafe in usage: constants determining number of sumilated particles are defined in the code, data is read from files (coordinates, velocity, acceleration etc are in separate files), files contain data presented in unobvious way. 
We need to elaborate the new standard for data representation, which will meet all basic requirements necessary to effectively describe a complex data structure including all virtual c. elegans systems (related to physical world) which we a going to simulate.

It would be great if we'll find a way to generate initial physical body of the worm (positions of the particles, spring and muscular connections between them) from 3D blender file -- at least the body shell and muscular system for the beginning. And it would be really great if this initial worm will be straight, not sinusoidally-bended.

Thoughts, opinions, propositions, advices on the subject are highly welcome!

**Comment by slarson** [comment]
Obsolete
