### ISSUE TITLE
Improve performance of Sibernetic computation step

### ISSUE THREAD

**Issue by gidili** [openworm/OpenWorm#74]
The [Sibernetic codebase](https://github.com/openworm/Smoothed-Particle-Hydrodynamics) is the C++ implementation of the c. elegans body.  It includes an implementation of the smoothed particle hydrodynamics algorithm.  From this algorithm, we implement multiple types of matter, including liquid, elastic, and hard surfaces.

Code base is here: https://github.com/openworm/Smoothed-Particle-Hydrodynamics

Several of the comments below also describe the Geppetto implementation of the SPH algorithm.  However, right now the C++ version (Sibernetic) has the latest updates and therefore performance boost should be focused there.

Simulations with > 10000 particles are fairly slow. Need to improve performance.

**Comment by slarson** [comment]
Sibernetic performance issues are continuing to be worked on over in the [Sibernetic repo](https://github.com/openworm/sibernetic); closing them off of here.
