### ISSUE TITLE
Create a D3 implementation of the C. elegans connectome HivePlot

### ISSUE THREAD

**Issue by slarson** [openworm/OpenWorm#89]
Building on the work of the previous issue #39 , open the source for the D3.js [implementation of a hive plot](http://bost.ocks.org/mike/hive/) and load up the c. elegans connectome data set in it so it can be interactively explored in a browser.

More guidance on how to go about this may be found on the [d3 mailing list](http://g.ua/WyNr)

**Comment by slarson** [comment]
@borismarin -- I saw the connectivity widget demoed at the last Geppetto meeting --very cool! Did the hive plot part get in there too yet?

**Comment by borismarin** [comment]
@slarson the infrastructure is there, but we need a more systematic way of
mapping qualitative domain specific info (e.g. how to determine if a cell
is inhibitory) and map that to visual representations in geppetto (e.g. map
a synaptic weight onto a line thickness). @adrianq and I will have a
meeting with @tarelli and @gidilli to discuss these issues next week. For
updates, see #235, #238, #323 .
If you want to play with a prototype, I (or @adrianq) can probably set up a
branch with our c302 / acnet specific code.

**Comment by borismarin** [comment]
Just saw this issue again while organising my waffle cards... I'd like to point out that the connectivity widget in geppetto has had four "incarnations" for quite a long time now (force, chord, hive, matrix), which look like that:
<img width="1440" alt="screen shot 2016-02-19 at 18 50 23" src="https://cloud.githubusercontent.com/assets/3452783/13185784/d5862c42-d73a-11e5-99d3-3cdf8d9ec33f.png">
(cortical layers 2/3 from Traub's model, not C. elegans!!)

The only thing preventing this issue from being closed is finding a way of mapping the cells in c302 into categories (sensory, motor, ...), which is not captured in neuroml2 systematically yet. In any case, it is indeed possible to hardcode that info via the conn. widget settings object (which is an obscene thing to do, as we are adding data via visualisation...), and we get something like that
<img width="1437" alt="screen shot 2016-02-20 at 12 41 26" src="https://cloud.githubusercontent.com/assets/3452783/13196768/f62113fa-d7cf-11e5-9c1f-f001dc0d8945.png">



for the c302 example in live.geppetto.org. Bottomline, I guess this issue can be closed and more specific ones added to address 1) qualitative info in nml2 2)specific settings for "useful" hive plots.

**Comment by gidili** [comment]
@borismarin looks AWESOME :beers:

**Comment by borismarin** [comment]
BTW, does that small motor->sensory projection make sense (thin orange band connecting [green slice]->[orange slice], or is that a bug in my code? (Notice the convention: chords emerge from the presynaptic category, but finish before "touching" the postsynaptic category)

**Comment by slarson** [comment]
@borismarin Let me echo @gidili here and say this is SICK (in a good way :) :+1 

It hadn't been obvious this has been working.  I've noticed that in the latest version of the ["user" docs](http://docs.geppetto.org/en/latest/usinggeppetto.html), there is no mention of the widgets or how to use them anymore, so it seems easy to overlook.

I had to do a search to find the old [using widgets](http://docs.geppetto.org/en/latest/usingwidgets.html) page, which finally does link down to showing those pictures.  But it seems we have lost the link unless I am just not seeing it on the user docs.

Do you know if this is on purpose, or should I submit a pull request to re-work the widgets back into the user documentation?  I think even better would be to pull some of these images up into the user docs page from the beginning, honestly, to highlight that this is possible.

After this is settled, I'd agree we should close this and re-open some more targeted derivative issues for connecting the c302 pieces in here.

Also, if I understand your question correctly, yes the small motor to sensory projection makes sense.  You can compare with the ones on [slide 22](https://docs.google.com/presentation/d/1E06SFi4z1XUbrGq6sW4zd6shGlhrCdDtJwtB1Ls_Y1k/edit#slide=id.g118e55567_0258) and [slide 23](https://docs.google.com/presentation/d/1E06SFi4z1XUbrGq6sW4zd6shGlhrCdDtJwtB1Ls_Y1k/edit#slide=id.g118e55567_0177) that I generated long ago.

**Comment by slarson** [comment]
Ah, now that I did a direct search, I do see that there are links to the using connectivity widgets page.

OK I will make a pull request to make this more obvious as it could be much clearer.

**Comment by slarson** [comment]
OK, this prompted me also to ask about how to improve the connectivity widget docs to better serve the closing of this one: openworm/org.geppetto.docs#32

**Comment by slarson** [comment]
OK closing this one and taking the rest of this issue over to the newly created openworm/CElegansNeuroML#57
